name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android32
            os: ubuntu-latest
            target: armv7-none-linux-androideabi
          - name: Android64
            os: ubuntu-latest
            target: aarch64-linux-android

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Circuit
        uses: actions/checkout@v4

      - name: Setup CLI
        uses: geode-sdk/actions/setup-cli@main

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          target: ${{ matrix.config.target }}
